import React from "react"
import styled from "@emotion/styled"
/**
 * `<Apply>` ('MacBook Air - 2')
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Apply/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e15ab589-9ec7-4e5e-b5b3-30257ed34938)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : unknown://undefined/10:23 -->
 */
export function Apply() {
  return (
    <RootWrapperApply>
      <Rectangle3 />
      <PersonalInformation>Personal Information:</PersonalInformation>
      <Education>Education:</Education>
      <CoverLetterResume>Cover Letter & Resume:</CoverLetterResume>
      <FullName>Full Name</FullName>
      <Address>Address</Address>
      <BirthDate>Birth Date</BirthDate>
      <PhoneNumber>Phone Number</PhoneNumber>
      <HighestEducationAchieved>
        Highest Education Achieved
      </HighestEducationAchieved>
      <HighestEducationAchieved>
        Highest Education Achieved
      </HighestEducationAchieved>
      <EMail>E-mail</EMail>
      <Degree>Degree</Degree>
      <CoverLetter>Cover Letter</CoverLetter>
      <Resume>Resume</Resume>
      <Down1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/00381e57-ff86-4fdc-bf98-d9b6a4d2a7d9"
        alt="image of Down1"
      />
      <Down4
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/de95de73-57c1-4cf9-bb27-7cc0d30db80b"
        alt="image of Down4"
      />
      <Down5
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5cf260d6-4476-49a8-a6cd-675cf02a5234"
        alt="image of Down5"
      />
      <Down2
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/db6e7fa8-7f7d-4931-bbfc-894b8d7cffb1"
        alt="image of Down2"
      />
      <Down3
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/146e7d64-5c89-4068-9549-cce16c9e7bd2"
        alt="image of Down3"
      />
      <UiWaterCorporation>UI WATER CORPORATION</UiWaterCorporation>
      <EmploymentApplication>Employment Application</EmploymentApplication>
      <Line1 />
      <Rectangle4 />
      <Rectangle10 />
      <Rectangle13 />
      <Rectangle15 />
      <Rectangle14 />
      <Rectangle16 />
      <Rectangle11 />
      <Rectangle12 />
      <Rectangle8 />
      <Rectangle9 />
      <Rectangle7 />
      <Rectangle5 />
      <Rectangle6 />
      <FirstName>First Name</FirstName>
      <StreetAddress>Street Address</StreetAddress>
      <City>City</City>
      <Month>Month</Month>
      <Day>Day</Day>
      <Year>Year</Year>
      <StateProvince>State/Province</StateProvince>
      <MiddleName>Middle Name</MiddleName>
      <LastName>Last Name</LastName>
      <Rectangle17 />
      <Rectangle18 />
      <Rectangle19 />
      <SubmitYourApplication>Submit Your Application</SubmitYourApplication>
      <CloudUpload2
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6c8ba804-e4b4-43de-a0ba-0d34ab9ca8e1"
        alt="image of CloudUpload2"
      />
      <UploadAFile>Upload a File</UploadAFile>
      <UploadAFile_0001>Upload a File</UploadAFile_0001>
      <DragAndDropFilesHere>Drag and drop files here</DragAndDropFilesHere>
      <DragAndDropFilesHere_0001>
        Drag and drop files here
      </DragAndDropFilesHere_0001>
    </RootWrapperApply>
  )
}

const RootWrapperApply = styled.div`
  min-height: 100vh;
  background-color: white;
  position: relative;
`

const Rectangle3 = styled.div`
  width: 1275px;
  height: 1698px;
  background-color: white;
  position: absolute;
  left: 0px;
  top: 0px;
`

const PersonalInformation = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 33px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 49px;
  top: 322px;
`

const Education = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 33px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 51px;
  top: 1392px;
`

const CoverLetterResume = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 33px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 53px;
  top: 1641px;
`

const FullName = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 49px;
  top: 448px;
`

const Address = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 57px;
  top: 688px;
`

const BirthDate = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 56px;
  top: 1026px;
`

const PhoneNumber = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 49px;
  top: 1232px;
`

const HighestEducationAchieved = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 51px;
  top: 1456px;
`

const EMail = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 619px;
  top: 1238px;
`

const Degree = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 613px;
  top: 1456px;
`

const CoverLetter = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 56px;
  top: 1717px;
`

const Resume = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 64px;
  top: 2081px;
`

const Down1 = styled.img`
  width: 32px;
  height: 36px;
  object-fit: cover;
  position: absolute;
  left: 318px;
  top: 1120px;
`

const Down4 = styled.img`
  width: 32px;
  height: 36px;
  object-fit: cover;
  position: absolute;
  left: 421px;
  top: 1559px;
`

const Down5 = styled.img`
  width: 32px;
  height: 36px;
  object-fit: cover;
  position: absolute;
  left: 986px;
  top: 1559px;
`

const Down2 = styled.img`
  width: 32px;
  height: 36px;
  object-fit: cover;
  position: absolute;
  left: 688px;
  top: 1125px;
`

const Down3 = styled.img`
  width: 32px;
  height: 36px;
  object-fit: cover;
  position: absolute;
  left: 1048px;
  top: 1126px;
`

const UiWaterCorporation = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 50px;
  font-family: Inter, sans-serif;
  font-weight: 500;
  line-height: 100px;
  text-align: center;
  width: 788px;
  position: absolute;
  left: 242px;
  top: 62px;
`

const EmploymentApplication = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 42px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 363px;
  top: 202px;
`

const Line1 = styled.div`
  width: 1230px;
  height: 0px;
  border-top: solid 2px rgb(159, 146, 146);
  position: absolute;
  left: -10px;
  top: 162px;
`

const Rectangle4 = styled.div`
  width: 310px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 50px;
  top: 548px;
  opacity: 0.1;
`

const Rectangle10 = styled.div`
  width: 334px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 50px;
  top: 1112px;
  opacity: 0.1;
`

const Rectangle13 = styled.div`
  width: 442px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 50px;
  top: 1549px;
  opacity: 0.1;
`

const Rectangle15 = styled.div`
  width: 442px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 611px;
  top: 1549px;
  opacity: 0.1;
`

const Rectangle14 = styled.div`
  width: 493px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 614px;
  top: 1318px;
  opacity: 0.1;
`

const Rectangle16 = styled.div`
  width: 493px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 49px;
  top: 1318px;
  opacity: 0.1;
`

const Rectangle11 = styled.div`
  width: 334px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 414px;
  top: 1112px;
  opacity: 0.1;
`

const Rectangle12 = styled.div`
  width: 334px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 772px;
  top: 1112px;
  opacity: 0.1;
`

const Rectangle8 = styled.div`
  width: 500px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 60px;
  top: 924px;
  opacity: 0.1;
`

const Rectangle9 = styled.div`
  width: 500px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 606px;
  top: 924px;
  opacity: 0.1;
`

const Rectangle7 = styled.div`
  width: 1053px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 57px;
  top: 774px;
  opacity: 0.1;
`

const Rectangle5 = styled.div`
  width: 310px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 790px;
  top: 550px;
  opacity: 0.1;
`

const Rectangle6 = styled.div`
  width: 310px;
  height: 55px;
  background-color: white;
  border: solid 4px black;
  border-radius: 10px;
  position: absolute;
  left: 420px;
  top: 550px;
  opacity: 0.1;
`

const FirstName = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 57px;
  top: 578px;
`

const StreetAddress = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 57px;
  top: 798px;
`

const City = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 60px;
  top: 955px;
`

const Month = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 56px;
  top: 1135px;
`

const Day = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 428px;
  top: 1138px;
`

const Year = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 775px;
  top: 1131px;
`

const StateProvince = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 608px;
  top: 958px;
`

const MiddleName = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 424px;
  top: 576px;
`

const LastName = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 802px;
  top: 574px;
`

const Rectangle17 = styled.div`
  width: 892px;
  height: 233px;
  background-color: rgb(242, 237, 237);
  border: solid 2px black;
  border-radius: 7px;
  position: absolute;
  left: 56px;
  top: 1829px;
`

const Rectangle18 = styled.div`
  width: 892px;
  height: 233px;
  background-color: rgb(242, 237, 237);
  border: solid 2px black;
  border-radius: 7px;
  position: absolute;
  left: 56px;
  top: 2189px;
`

const Rectangle19 = styled.div`
  width: 400px;
  height: 100px;
  background-color: rgb(34, 66, 14);
  border: solid 2px black;
  border-radius: 7px;
  position: absolute;
  left: 351px;
  top: 2594px;
`

const SubmitYourApplication = styled.span`
  color: white;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 396px;
  top: 2594px;
`

const CloudUpload2 = styled.img`
  width: 100px;
  height: 100px;
  object-fit: cover;
  position: absolute;
  left: 451px;
  top: 2206px;
`

const UploadAFile = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 421px;
  top: 1917px;
`

const UploadAFile_0001 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 27px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 421px;
  top: 2277px;
`

const DragAndDropFilesHere = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 391px;
  top: 1960px;
`

const DragAndDropFilesHere_0001 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 19px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  line-height: 100px;
  text-align: center;
  position: absolute;
  left: 391px;
  top: 2320px;
`
